# Site settings
title: Oscar K. Sandoval (mtfalls)
email: Setting up my own email server...
description: "Game designer, web developer, virtual reality enthusiast, all-around weeb."
baseurl: ""
url: "https://mtfalls.github.io/"
twitter_username: _mtfalls_
github_username:  mtfalls

# Build settings
markdown: kramdown
permalink: pretty

#Collections
collections:
  projects:
    output: true

  tutorials:
    output: true

theme: jekyll-theme-leap-day