# Site settings
title: Oscar K. Sandoval (mtfalls)
email: goldjet45@gmail.com
description: "Personal musings from yours truly. Let's talk games, music, and coding!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: oks_mtfalls
github_username:  mtfalls

# Build settings
markdown: kramdown
permalink: pretty
