# Site settings
title: Oscar K. Sandoval (mtfalls)
email: oks.mtfalls@gmail.com
description: "Personal musings from yours truly. Let's talk games, music, and coding!"
baseurl: ""
url: "https://mtfalls.github.io/"
twitter_username: oks_mtfalls
github_username:  mtfalls

# Build settings
markdown: kramdown
permalink: pretty
