# Site settings
title: Oscar K. Sandoval (mtfalls)
email: oks.mtfalls@gmail.com
description: "A wanderer isn't always lost."
baseurl: ""
url: "https://mtfalls.github.io/"
twitter_username: oks_mtfalls
github_username:  mtfalls

# Build settings
markdown: kramdown
permalink: pretty

#Collections
collections:
  projects:
    output: true

  tutorials:
    output: true
